# Project: Ecom Copilot
# Purpose: Audit repo + API routes so we don't recreate existing work.
# Generated by scaffolding.

param(
  [string]$Root = ""
)

$ErrorActionPreference = "Stop"

if (-not $Root) { $Root = Split-Path -Parent $PSScriptRoot }

Write-Host "=== Ecom Copilot Repo Audit ===" -ForegroundColor Cyan
Write-Host ("Root: {0}" -f $Root) -ForegroundColor White

function Try-Run([string]$Label, [scriptblock]$Fn) {
  try {
    Write-Host ""
    Write-Host ("--- {0} ---" -f $Label) -ForegroundColor Cyan
    & $Fn
  } catch {
    Write-Host ("WARN: {0} failed: {1}" -f $Label, $_.Exception.Message) -ForegroundColor Yellow
  }
}

Try-Run "Git status" {
  $branch = (git -C $Root rev-parse --abbrev-ref HEAD 2>$null)
  if ($branch) { Write-Host ("Branch: {0}" -f $branch) -ForegroundColor White }
  git -C $Root status -sb
}

Try-Run "Top-level structure" {
  Get-ChildItem -LiteralPath $Root -Force | Select-Object Name, Mode, LastWriteTime | Format-Table -AutoSize
}

Try-Run "Keys folder (names only)" {
  $keys = Join-Path $Root "keys"
  if (Test-Path -LiteralPath $keys) {
    Get-ChildItem -LiteralPath $keys -Force | Select-Object Name, LastWriteTime | Format-Table -AutoSize
  } else {
    Write-Host "No keys/ folder found." -ForegroundColor Yellow
  }
}

$server = Join-Path $Root "api\server.py"
if (-not (Test-Path -LiteralPath $server)) {
  Write-Host ("ERROR: api\server.py not found at: {0}" -f $server) -ForegroundColor Red
  exit 1
}

$content = Get-Content -LiteralPath $server -Raw

Try-Run "API requirements check (httpx, boto3)" {
  $req = Join-Path $Root "api\requirements.txt"
  if (-not (Test-Path -LiteralPath $req)) {
    Write-Host "requirements.txt not found in api/." -ForegroundColor Yellow
  } else {
    $reqText = Get-Content -LiteralPath $req -Raw
    foreach ($pkg in @("httpx","boto3")) {
      if ($reqText -match ("(?m)^\s*" + [Regex]::Escape($pkg) + "(\s|==|>=|<=|~=|$)")) {
        Write-Host ("OK: {0} present" -f $pkg) -ForegroundColor Green
      } else {
        Write-Host ("MISSING: {0}" -f $pkg) -ForegroundColor Yellow
      }
    }
  }
}

Try-Run "Route inventory + duplicates" {
  $rx = [regex]'@app\.(get|post|put|delete)\(\s*"([^"]+)"'
  $matches = $rx.Matches($content)

  $routes = @()
  foreach ($m in $matches) {
    $routes += [pscustomobject]@{
      Method = $m.Groups[1].Value.ToUpper()
      Path   = $m.Groups[2].Value
    }
  }

  Write-Host ("Total route decorators found: {0}" -f $routes.Count) -ForegroundColor White

  $dupes = $routes | Group-Object Method, Path | Where-Object { $_.Count -gt 1 } | Sort-Object Count -Descending
  if ($dupes.Count -gt 0) {
    Write-Host ""
    Write-Host "DUPLICATES (same method+path appears more than once):" -ForegroundColor Yellow
    $dupes | ForEach-Object {
      "{0}  {1}  (x{2})" -f ($_.Group[0].Method), ($_.Group[0].Path), $_.Count
    } | ForEach-Object { Write-Host $_ -ForegroundColor Yellow }
  } else {
    Write-Host "OK: No duplicate method+path decorators detected." -ForegroundColor Green
  }

  Write-Host ""
  Write-Host "Sample routes (first 25):" -ForegroundColor Cyan
  $routes | Select-Object -First 25 | Format-Table -AutoSize
}

Try-Run "Existing Amazon-related code scan" {
  $hits = @(
    "integrations/amazon",
    "spapi_oauth_code",
    "selling_partner_id",
    "AMAZON_",
    "secretsmanager",
    "boto3",
    "api.amazon.com/auth/o2/token",
    "/apps/authorize/consent"
  )

  foreach ($h in $hits) {
    if ($content -match [regex]::Escape($h)) {
      Write-Host ("FOUND: {0}" -f $h) -ForegroundColor Green
    } else {
      Write-Host ("not found: {0}" -f $h) -ForegroundColor DarkGray
    }
  }
}

Write-Host ""
Write-Host "=== NEXT ===" -ForegroundColor Cyan
Write-Host "1) We confirm what exists (this audit output)." -ForegroundColor White
Write-Host "2) Then we add ONE tiny endpoint, commit, push, deploy." -ForegroundColor White
