@echo off
setlocal

REM Project: Ecom Copilot
REM Purpose: Run repo audit and keep window open
REM Generated by scaffolding.

for %%I in ("%~dp0..") do set "ROOT=%%~fI"

echo ROOT=%ROOT%
echo.

if not exist "%ROOT%\diagnostic\diagnostic_repo_audit.ps1" (
  echo ERROR: Missing %ROOT%\diagnostic\diagnostic_repo_audit.ps1
  echo.
  pause
  exit /b 1
)

powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%\diagnostic\diagnostic_repo_audit.ps1" -Root "%ROOT%"

echo.
echo ExitCode=%ERRORLEVEL%
echo.
pause
endlocal
