# Project: Ecom Copilot
# Purpose: Patch api\requirements.txt to include httpx + boto3 (no duplicates)
# Generated by scaffolding.

param(
  [string]$Root = ""
)

$ErrorActionPreference = "Stop"
if (-not $Root) { $Root = Split-Path -Parent $PSScriptRoot }

$reqFile = Join-Path $Root "api\requirements.txt"
Write-Host "Patching: $reqFile" -ForegroundColor Cyan

if (-not (Test-Path -LiteralPath $reqFile)) {
  New-Item -ItemType File -Force -Path $reqFile | Out-Null
}

$raw = Get-Content -LiteralPath $reqFile -Raw -ErrorAction Stop
$lines = @()
if ($raw) { $lines = ($raw -split "`r?`n") }

function Has-Package([string[]]$arr, [string]$name) {
  return ($arr | Where-Object { $_ -match ("^\s*" + [Regex]::Escape($name) + "(\s|==|>=|<=|~=|$)") }).Count -gt 0
}

foreach ($pkg in @("httpx","boto3")) {
  if (-not (Has-Package $lines $pkg)) {
    Write-Host "Adding $pkg" -ForegroundColor Yellow
    $lines += $pkg
  } else {
    Write-Host "Already present: $pkg" -ForegroundColor DarkGray
  }
}

# Write UTF-8 without BOM
$newText = (($lines | Where-Object { $_ -ne $null }) -join "`r`n") + "`r`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($reqFile, $newText, $utf8NoBom)

Write-Host "OK: requirements patched." -ForegroundColor Green
