# Project: Ecom Copilot
# Purpose: Patch api\requirements.txt to include httpx + boto3 (no duplicates), UTF-8 without BOM
# Generated by scaffolding.

param(
  [string]$Root = ""
)

$ErrorActionPreference = "Stop"

if (-not $Root) { $Root = Split-Path -Parent $PSScriptRoot }

$reqFile = Join-Path $Root "api\requirements.txt"
Write-Host "Patching: $reqFile" -ForegroundColor Cyan

if (-not (Test-Path -LiteralPath $reqFile)) {
  New-Item -ItemType File -Force -Path $reqFile | Out-Null
}

# Read lines safely
$raw = Get-Content -LiteralPath $reqFile -Raw -ErrorAction Stop
$lines = @()
if ($raw) {
  $lines = ($raw -split "`r?`n")
}

function Has-Package([string[]]$arr, [string]$name) {
  return ($arr | Where-Object { $_ -match ("^\s*" + [Regex]::Escape($name) + "(\s|==|>=|<=|~=|$)") }).Count -gt 0
}

$wanted = @("httpx", "boto3")

foreach ($pkg in $wanted) {
  if (-not (Has-Package $lines $pkg)) {
    Write-Host "Adding $pkg" -ForegroundColor Yellow
    $lines += $pkg
  } else {
    Write-Host "Already present: $pkg" -ForegroundColor DarkGray
  }
}

# Normalize: remove empty trailing lines
$lines = $lines | Where-Object { $_ -ne $null }
while ($lines.Count -gt 0 -and ($lines[-1].Trim() -eq "")) {
  $lines = $lines[0..($lines.Count-2)]
}

$newText = ($lines -join "`r`n") + "`r`n"

# Write UTF-8 without BOM (avoids cmd/pip oddities)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($reqFile, $newText, $utf8NoBom)

Write-Host "OK: requirements patched." -ForegroundColor Green
