<#
  Project: Ecom Copilot
  File:    kmc_pricing_run.ps1
  Purpose: Run the KMC pricing engine v1 (CSV -> repriced CSV).
  Generated by scaffolding.
#>

param(
    [string]$Root = "C:\Users\Kylem\OneDrive - Copy and Paste LLC\Bwaaack\Ecom Copilot"
)

$ErrorActionPreference = "Stop"

Write-Host "Running KMC pricing engine..." -ForegroundColor Cyan
Write-Host "Root: $Root"
Write-Host ""

Set-Location $Root

# If 'python' is not on PATH, you can hardcode your Python 3.13 path here instead.
# Example:
#   & "C:\Users\Kylem\AppData\Local\Programs\Python\Python313\python.exe" ".\py\kmc_pricing_engine.py"

python ".\py\kmc_pricing_engine.py"
