@echo off
setlocal
REM Project: Ecom Copilot
REM Purpose: Open the ChatGPT handoff doc quickly
REM Generated by scaffolding.

for %%I in ("%~dp0..") do set "ROOT=%%~fI"
notepad "%ROOT%\docs\CHATGPT_HANDOFF.md"
endlocal
