@echo off
setlocal
REM Project: Ecom Copilot
REM Purpose: Run requirements patch to add httpx + boto3
REM Generated by scaffolding.

for %%I in ("%~dp0..") do set "ROOT=%%~fI"

echo ROOT=%ROOT%
echo.

powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%\ps1\patches\patch_api_requirements_add_httpx_boto3.ps1" -Root "%ROOT%"

echo.
echo ExitCode=%ERRORLEVEL%
echo.
pause
endlocal
