@echo off
setlocal
REM Project: Ecom Copilot
REM Purpose: Run patch to add Amazon Connect start endpoint
REM Generated by scaffolding.

for %%I in ("%~dp0..") do set "ROOT=%%~fI"

echo ROOT=%ROOT%
echo.

powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%\ps1\patches\patch_api_server_add_amazon_start.ps1" -Root "%ROOT%"

echo.
echo ExitCode=%ERRORLEVEL%
echo.
pause
endlocal
